# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="3"
SUPPORT_PYTHON_ABIS="1"
DISTUTILS_SRC_TEST="setup.py"

inherit distutils

MY_PN="Markups"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A wrapper around various text markups"
HOMEPAGE="http://launchpad.net/python-markups"
SRC_URI="http://pypi.python.org/packages/source/M/Markups/${MY_P}.tar.gz"

LICENSE="BSD-2"
KEYWORDS="~amd64"
SLOT="0"
IUSE="examples"


S="${WORKDIR}/${MY_P}"

src_install() {
	distutils_src_install
	if use examples; then
		insinto /usr/share/doc/"${PF}"/
		doins -r examples
	fi
}
